### PR TITLE
Allow for changing label of button

### PR DESCRIPTION
**Pull request by ladyada**
mostly a refactor, so button text can change

### CODE REVIEW

**Review by makermelissa — APPROVED** [review]
Tested and works great with my calculator example.

**Comment by ladyada** [comment]
huzzah! wanna bump both?

**Comment by makermelissa** [comment]
Yep, was just about to do that.

**Comment by makermelissa** [comment]
I should note that while this update didn't break the examples, the examples should probably be updated to work with Beta 5, which is why I approved it. I can create an issue for that.

**Comment by makermelissa** [comment]
@kattni, could you fix the API keys for  https://github.com/adafruit/Adafruit_CircuitPython_Display_Shapes and https://github.com/adafruit/Adafruit_CircuitPython_Display_Button when you get a chance? Both are failing to release on travis.

**Comment by kattni** [comment]
@ladyada Fixed.

**Pull request merged**
